/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
typedef unsigned int 		uint32_t;
typedef volatile uint32_t 	vuint32_t;
#define RCC_BASE 			0X40021000
#define PORTA_BASE 			0X40010800

#define RCC_APB2ENR 		*((vuint32_t*)(RCC_BASE + 0x18))
#define GPIOA_CRH 			*((vuint32_t*)(PORTA_BASE + 0x04))
#define GPIOA_ODR 			*((vuint32_t*)(PORTA_BASE + 0x0C))

typedef union
{
	vuint32_t all_fields;
	struct
	{
		vuint32_t reserved : 13 ;
		vuint32_t pin_13 : 1;
	}SPIN;

}R_ODR_t;

volatile R_ODR_t * R_ODR = (volatile R_ODR_t *)(PORTA_BASE + 0x0c);
unsigned char g_variable[3]={1,2,3};
unsigned char const const_variable[3]={1,2,3};
unsigned int bss_variable=0 ;

int main(void)
{
	RCC_APB2ENR |= (1<<2);
	GPIOA_CRH 	&= (0Xff0fffff);
	GPIOA_CRH	|= (0x00200000);
    /* Loop forever */
    int i;
	while(1)
	{
		//GPIOA_ODR |= (1<<13);
		R_ODR->SPIN.pin_13 = 1;
		for(i=0 ; i<5000 ; i++); //delay
		GPIOA_ODR &= ~(1<<13);
		//R_ODR->SPIN.pin_13 = 0;
		for(i=0 ; i<5000 ; i++); //delay
	}
}
